version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - pronix
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - pronix
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - pronix
