apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-config
  labels:
    {{- include "netdata.labels" . | nindent 4 }}
data:
  netdata-config.yaml: "---\nsubnets: ['10.0.0.0/24']\ninterval: 60\nttl: 3600\nkeaapi: 'http://kea-primary.kea-dhcp.svc.cluster.local:8000/'\ninteface: 'wlp2s0'\nippriority: ['nmap','ndp','dhcp']\nhostnamepriority: ['dhcp','nmap','ndp']\n"
