name: DockerImage2Harbor

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: core.harbor.onmetal.de/onmetal/netdata-ipam

jobs:
  push:
    runs-on: self-hosted
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        env:
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest

      - name: Login to harbor
        uses: docker/login-action@v1
        with:
          registry: core.harbor.onmetal.de
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Deploy to Docker registry
        run: docker push $IMAGE_NAME:latest
