name: Pull Request Code test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - '**.md'
      - 'deploy/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'deploy/**'
      - 'docs/**'
      - '**/*.md'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make build
      - run: make test
