name: Pull Request Code test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - '**.md'
      - 'deploy/**'
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - 'deploy/**'
      - 'docs/**'
      - '**/*.md'

jobs:
  run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: |
          mkdir -p ~/.ssh
          for key in rsa ecdsa ed25519; do
            ssh-keyscan -t $key github.com 2>/dev/null >> ~/.ssh/known_hosts
          done
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - run: ./hack/setup-git-redirect.sh
      - run: make build
      - run: make test
